services:
  eureka:
    build: ../eureka
    container_name: eureka-service
    ports:
      - "8761:8761"
    env_file:
      - .env
    networks:
      - backend-net

  gateway:
    build: ../gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - backend-net

  commerce:
    build: ../commerce
    container_name: commerce-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - payment
    networks:
      - backend-net

  payment:
    build: ../payment
    container_name: payment-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    networks:
      - backend-net

  settlement:
    build: ../settlement
    container_name: settlement-service
    ports:
      - "8083:8083"
    env_file:
      - .env
    networks:
      - backend-net
  commerce-ui:
    build: ../commerce-ui
    container_name: commerce-ui-service
    ports:
      - "8084:8084"
    env_file:
      - .env
    networks:
      - backend-net
networks:
  backend-net:
    driver: bridge