spring:
  application:
    name: commerce-ui

server:
  port: 8084

commerce:
  api:
    url: http://localhost:8080
    prefix: /api/commerce

payment:
  api:
    url: http://localhost:8080
    prefix: /api/payment

toss:
  client-key: ${CLIENT_KEY}
  secret-key: ${SECRET_KEY}
